# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="mrs_spellings",
    version="0.1.0",
    description="a micro utility for generating plausible misspellings",
    python_requires="==3.*,>=3.4.0",
    author="CircArgs",
    author_email="quebecname@gmail.com",
    license="MIT",
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=[],
    extras_require={
        "dev": [
            "dephell==0.*,>=0.8.3",
            "pylint==2.*,>=2.5.2",
            "pytest==3.*,>=3.0.0",
            "pytest-cov==2.*,>=2.4.0",
        ]
    },
)
