name: test
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code...
        id: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: testing
        id: testing
        uses: ./.github/actions/testing
        env:
          CODECOV_TOKEN: "6213863a-d57e-4852-a36a-85ff6f7d0ffb"
        #   GITPASS: ${{ secrets.GITPASS }}
        #   EMAIL: ${{ secrets.EMAIL }}
